default: &DEFAULT
  path: "../../runs"
  visualize_iterations: True
  save_iterations: False
  pretrained_path: ""
  offline_training: False
  pure_mcts: False
  mcts: &DEFAULT_MCTS
    samples: 50
    temp: 1.0
    cpuct: 4
    observation_weight: 0.5
  replay_buffer:
    size: 30000
  train: &DEFAULT_TRAIN
    iterations: 150
    episodes: 8
    samples_per_iteration: 1024
    lr: 0.0001 #1e-4
    weight_decay: 0.0001 #1e-4
    policy_loss_factor: 1.0
    value_loss_factor: 1.0
    batch_size: 32
    n_processes: 8
  ranked_reward:
    size: 250
    threshold: 0.75
    update_rank: True
  house: &DEFAULT_HOUSE
    elevator_capacity: 10
    number_of_elevators: 1
    number_of_floors: 3


debugging_default:
  <<: *DEFAULT
  visualize_iterations: False
  mcts:
    <<: *DEFAULT_MCTS
    samples: 5
  train:
    <<: *DEFAULT_TRAIN
    iterations: 150
    episodes: 4
    samples_per_iteration: 16
    lr: 0.0001 #1e-4
    weight_decay: 0.0001 #1e-4
    policy_loss_factor: 1.0
    value_loss_factor: 1.0
    batch_size: 4
    n_processes: 4

without_early_reward:
  <<: *DEFAULT
  mcts:
    <<: *DEFAULT_MCTS
    observation_weight: 0

2elev_3floor:
  <<: *DEFAULT
  house:
    <<: *DEFAULT_HOUSE
    number_of_elevators: 2
    number_of_floors: 3

1elev_5floor:
  <<: *DEFAULT
  house:
    <<: *DEFAULT_HOUSE
    number_of_elevators: 1
    number_of_floors: 5

2elev_5floor:
  <<: *DEFAULT
  house:
    <<: *DEFAULT_HOUSE
    number_of_elevators: 2
    number_of_floors: 5

1elev_7floor:
  <<: *DEFAULT
  house:
    <<: *DEFAULT_HOUSE
    number_of_elevators: 1
    number_of_floors: 7

2elev_7floor:
  <<: *DEFAULT
  house:
    <<: *DEFAULT_HOUSE
    number_of_elevators: 2
    number_of_floors: 7

save_model:
  <<: *DEFAULT
  save_iterations: True

load_model:
  <<: *DEFAULT
  pretrained_path: "/home/pfeifletim/pycharm/runs/2020-07-15_12:30:39_save_model/model_save_3.pth"
  offline_training: True

many_samples:
  <<: *DEFAULT
  mcts:
    samples: 3000

default_pure_MCTS:
  <<: *DEFAULT
  pure_mcts: True

10stores_mctsuniform:
  <<: *DEFAULT
  house:
    <<: *DEFAULT_HOUSE
    number_of_floors: 10
    elevator_capacity: 20

10stores_mctsuniform_many_samples:
  <<: *DEFAULT
  mcts:
    <<: *DEFAULT_MCTS
    samples: 200
  train:
    iterations: 100
    episodes: 16
    samples_per_iteration: 2048
    lr: 0.0001 #1e-3
    weight_decay: 0.0001 #1e-4
    policy_loss_factor: 1.0
    value_loss_factor: 1.0
    batch_size: 32
    n_processes: 8
  house:
    <<: *DEFAULT_HOUSE
    number_of_floors: 10
    elevator_capacity: 20

optimized_params:
  <<: *DEFAULT
  mcts:
    <<: *DEFAULT_MCTS
    samples: 40
  train:
    <<: *DEFAULT_TRAIN
    episodes: 16
    samples_per_iteration: 4096
    lr: 0.001 #1e-3
    weight_decay: 0.0001 #1e-4
    batch_size: 128
  replay_buffer:
    size: 7000
